const express = require("express");
const router = express.Router();
const schedule = require("node-schedule");
const generateEmailCode = require("../utils/emailCode");

let job = null;
router.post("/addScheduleJob", (request, response) => {
  const { scheduled, email } = request.body;
  job = schedule.scheduleJob(scheduled, () => {
    generateEmailCode(email)
      .then((result) => {
        console.log(
          `The email verification code generated by the current scheduled task is ${result}`
        );
      })
      .catch((error) => {
        console.log(error);
      });
  });
  if (job) {
    response.send({
      code: 200,
      message: "创建成功",
    });
  }
});

router.post("/cancelScheduleJob", (request, response) => {
  if (job) {
    job.cancel();
    response.send({
      code: 200,
      message: "取消成功",
    });
  } else {
    response.send({
      code: 200,
      message: "任务不存在",
    });
  }
});

module.exports = router;
