import React from "react";
import { FormattedMessage } from "react-intl";
import {
  DashboardOutlined,
  CompassOutlined,
  UserOutlined,
  TeamOutlined,
  SettingOutlined,
  UserSwitchOutlined,
  SolutionOutlined,
  EditOutlined,
  FileOutlined,
  EyeInvisibleOutlined,
  FieldTimeOutlined,
  CopyOutlined,
  AreaChartOutlined,
  LineChartOutlined,
  BarChartOutlined,
  PieChartOutlined,
  BoxPlotOutlined,
  DotChartOutlined,
  SlidersOutlined,
  EnvironmentOutlined,
  AppstoreOutlined,
  FileExcelOutlined,
  FileZipOutlined,
  FileTextOutlined,
  FileMarkdownOutlined,
  FireOutlined,
  QrcodeOutlined,
  PlayCircleOutlined,
  FilePdfOutlined,
  StopOutlined,
  LockOutlined,
  AlertOutlined,
  FrownOutlined,
} from "@ant-design/icons";

const menuList: Array<object> = [
  {
    label: <FormattedMessage id="menulist.home" />,
    key: "/home",
    icon: <DashboardOutlined />,
    roles: ["root", "admin", "user"],
  },
  {
    label: <FormattedMessage id="menulist.guide" />,
    key: "/guide",
    icon: <CompassOutlined />,
    roles: ["root", "admin", "user"],
  },
  {
    label: <FormattedMessage id="menulist.user_menu" />,
    key: "/user-menu",
    icon: <UserOutlined />,
    roles: ["root", "admin"],
    children: [
      {
        label: <FormattedMessage id="menulist.user_list" />,
        key: "/user-menu/user-list",
        icon: <TeamOutlined />,
        roles: ["root", "admin"],
      },
    ],
  },
  {
    label: <FormattedMessage id="menulist.setting_menu" />,
    key: "/setting-menu",
    icon: <SettingOutlined />,
    roles: ["root", "admin", "user"],
    children: [
      {
        label: <FormattedMessage id="menulist.user_setting" />,
        key: "/setting-menu/user-setting",
        icon: <UserSwitchOutlined />,
        roles: ["root", "admin", "user"],
        children: [
          {
            label: <FormattedMessage id="menulist.basic_info" />,
            key: "/setting-menu/user-setting/basic-info",
            icon: <SolutionOutlined />,
            roles: ["root", "admin", "user"],
          },
          {
            label: <FormattedMessage id="menulist.modify_password" />,
            key: "/setting-menu/user-setting/modify-password",
            icon: <EditOutlined />,
            roles: ["root", "admin", "user"],
          },
        ],
      },
    ],
  },
  {
    label: <FormattedMessage id="menulist.file_admin" />,
    key: "/file-admin",
    icon: <FileOutlined />,
    roles: ["root", "admin", "user"],
  },
  {
    label: <FormattedMessage id="menulist.authority" />,
    key: "/authority",
    icon: <EyeInvisibleOutlined />,
    roles: ["root", "admin", "user"],
  },
  {
    label: <FormattedMessage id="menulist.schedule" />,
    key: "/schedule",
    icon: <FieldTimeOutlined />,
    roles: ["root", "admin", "user"],
  },
  {
    label: <FormattedMessage id="menulist.icon" />,
    key: "/icon",
    icon: <CopyOutlined />,
    roles: ["root", "admin", "user"],
  },
  {
    label: <FormattedMessage id="menulist.chart" />,
    key: "/chart",
    icon: <AreaChartOutlined />,
    roles: ["root", "admin", "user"],
    children: [
      {
        label: <FormattedMessage id="menulist.chart.line" />,
        key: "/chart/line",
        icon: <LineChartOutlined />,
        roles: ["root", "admin", "user"],
      },

      {
        label: <FormattedMessage id="menulist.chart.bar" />,
        key: "/chart/bar",
        icon: <BarChartOutlined />,
        roles: ["root", "admin", "user"],
      },
      {
        label: <FormattedMessage id="menulist.chart.pie" />,
        key: "/chart/pie",
        icon: <PieChartOutlined />,
        roles: ["root", "admin", "user"],
      },
      {
        label: <FormattedMessage id="menulist.chart.key_board" />,
        key: "/chart/key-board",
        icon: <BoxPlotOutlined />,
        roles: ["root", "admin", "user"],
      },
      {
        label: <FormattedMessage id="menulist.chart.water" />,
        key: "/chart/water",
        icon: <DotChartOutlined />,
        roles: ["root", "admin", "user"],
      },
      {
        label: <FormattedMessage id="menulist.chart.mix" />,
        key: "/chart/mix",
        icon: <SlidersOutlined />,
        roles: ["root", "admin", "user"],
      },
      {
        label: <FormattedMessage id="menulist.chart.china" />,
        key: "/chart/china",
        icon: <EnvironmentOutlined />,
        roles: ["root", "admin"],
      },
    ],
  },
  {
    label: <FormattedMessage id="menulist.module" />,
    key: "/module",
    icon: <AppstoreOutlined />,
    roles: ["root", "admin", "user"],
    children: [
      {
        label: <FormattedMessage id="menulist.module.excel" />,
        key: "/module/excel",
        icon: <FileExcelOutlined />,
        roles: ["root", "admin", "user"],
      },
      {
        label: <FormattedMessage id="menulist.module.zip" />,
        key: "/module/zip",
        icon: <FileZipOutlined />,
        roles: ["root", "admin", "user"],
      },
      {
        label: <FormattedMessage id="menulist.module.rich_text" />,
        key: "/module/rich-text",
        icon: <FileTextOutlined />,
        roles: ["root", "admin", "user"],
      },
      {
        label: <FormattedMessage id="menulist.module.mark_down" />,
        key: "/module/mark-down",
        icon: <FileMarkdownOutlined />,
        roles: ["root", "admin", "user"],
      },
      {
        label: <FormattedMessage id="menulist.module.type_effect" />,
        key: "/module/type-effect",
        icon: <FireOutlined />,
        roles: ["root", "admin", "user"],
      },
      {
        label: <FormattedMessage id="menulist.module.qrcode" />,
        key: "/module/qrcode",
        icon: <QrcodeOutlined />,
        roles: ["root", "admin", "user"],
      },
      {
        label: <FormattedMessage id="menulist.module.player" />,
        key: "/module/player",
        icon: <PlayCircleOutlined />,
        roles: ["root", "admin", "user"],
      },
      {
        label: <FormattedMessage id="menulist.module.pdf_preview" />,
        key: "/module/pdf-preview",
        icon: <FilePdfOutlined />,
        roles: ["root", "admin", "user"],
      },
    ],
  },
  {
    label: <FormattedMessage id="menulist.error" />,
    key: "/error",
    icon: <StopOutlined />,
    roles: ["root", "admin", "user"],
    children: [
      {
        label: <FormattedMessage id="menulist.error.no_authority" />,
        key: "/error/no-authority",
        icon: <LockOutlined />,
        roles: ["root", "admin", "user"],
      },
      {
        label: <FormattedMessage id="menulist.error.not_found" />,
        key: "/error/not-found",
        icon: <FrownOutlined />,
        roles: ["root", "admin", "user"],
      },
      {
        label: <FormattedMessage id="menulist.error.server_error" />,
        key: "/error/server-error",
        icon: <AlertOutlined />,
        roles: ["root", "admin", "user"],
      },
    ],
  },
];

export default menuList;
